use sqldb;
INSERT INTO pivotTest VALUES('유재석','겨울',10);
INSERT INTO pivotTest VALUES('강호동','여름',15);
INSERT INTO pivotTest VALUES('유재석','가을',25);
INSERT INTO pivotTest VALUES('유재석','봄',3);
INSERT INTO pivotTest VALUES('유재석','봄',37);
INSERT INTO pivotTest VALUES('강호동','겨울',40);
INSERT INTO pivotTest VALUES('유재석','여름',14);
INSERT INTO pivotTest VALUES('유재석','겨울',22);
INSERT INTO pivotTest VALUES('강호동','여름',64);
SELECT * FROM pivotTest;
